=== valentinaPrometeo/lm_asir/2da_Eva/repasoXML_JSON/assets/configuracion_web.dtd
<!ELEMENT configuracion_web (nombre, dominio, tecnologias, secciones, configuracion_server)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dominio (#PCDATA)>
<!ELEMENT tecnologias (tecnologia+)>
<!ELEMENT tecnologia (#PCDATA)>
<!ELEMENT secciones (seccion+)>
<!ELEMENT seccion (#PCDATA)>
<!ELEMENT configuracion_server (puerto, base_datos)>
<!ELEMENT puerto (#PCDATA)>
<!ELEMENT base_datos (#PCDATA)>

=== valentinaPrometeo/lm_asir/2da_Eva/repasoXML_JSON/assets/configuracion_web.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    Crea un XML con la info de un sitio web:
     - Nombre del sitio
     - Dominio
     - Tecnologias utilizadas (con subelementos tecnologia con valores como HTML, JS, CSS)
     - Secciones del sitio (con subelementos seccion con valores como Inicio, Blog, Contacto)
     - Configuracion servidor (con subelementos puerto y base datos)
-->

<!-- Document type definition (DTD) en el propio XML -->
<!-- <!DOCTYPE configuracion_web [
    <!ELEMENT configuracion_web (nombre, dominio, tecnologias, secciones, configuracion_server)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT dominio (#PCDATA)>
    <!ELEMENT tecnologias (tecnologia+)>
    <!ELEMENT tecnologia (#PCDATA)>
    <!ELEMENT secciones (seccion+)>
    <!ELEMENT seccion (#PCDATA)>
    <!ELEMENT configuracion_server (puerto, base_datos)>
    <!ELEMENT puerto (#PCDATA)>
    <!ELEMENT base_datos (#PCDATA)>
]> -->

<!-- Enlazar a un fichero externo DTD -->
<!-- <!DOCTYPE configuracion_web SYSTEM "configuracion_web.dtd"> -->

<!-- Enlazar a un XSD existente  -->
<!-- <configuracion_web xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="configuracion_web.xsd"> -->

<!-- Enlazar a un XSD existente mediante XML model -->
<?xml-model href="configuracion_web.xsd"?>
<configuracion_web>
    <nombre>CucuSoft</nombre>
    <dominio>www.cucusoft.ro</dominio>
    <tecnologias>
        <tecnologia>HTML</tecnologia>
        <tecnologia>CSS</tecnologia>
        <tecnologia>JS</tecnologia>
    </tecnologias>
    <secciones>
        <seccion>Inicio</seccion>
        <seccion>Blog</seccion>
        <seccion>Contacto</seccion>
    </secciones>
    <configuracion_server>
        <puerto>8080</puerto>
        <base_datos>PostgreSQL</base_datos>
    </configuracion_server>
</configuracion_web>
